[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project]
name = "srflawscry"
version = "1.0.1"
maintainers = [
  { name = "Egor Chistov", email = "egorchistov@mail.ru" }
]
description = "..."
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["dependencies"]
license = "BSD-3-Clause"
license-files = ["LICENSE"]

[project.optional-dependencies]
dev = [
  "playwright>=1.56",
  "pre-commit>=4.5",
  "pytest>=9.0",
]

[project.urls]
Homepage = "https://github.com/msu-video-group/srflawscry"
Issues = "https://github.com/msu-video-group/srflawscry/issues"
